import Link from "next/link";
import { notFound } from "next/navigation";
import { AppShell } from "../../components/AppShell";
import { LiveEventCard } from "../../components/LiveEventCard";
import { VenueFavorite } from "../../components/VenueFavorite";
import { SearchBackLink } from "../../components/SearchBackLink";
import { REGION_LABELS, formatNumber, getEventsByVenue, getVenue, isPastEvent } from "../../lib/livehouse-data";
export default async function VenuePage({ params }: { params: Promise<{venueId: string}> }) {
 const { venueId } = await params; const venue = getVenue(venueId); if (!venue) notFound();
 const events = getEventsByVenue(venue.id); const upcoming = events.filter(e=>!isPastEvent(e.eventDate)); const past = events.filter(e=>isPastEvent(e.eventDate));
 const map = `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(venue.name+' '+venue.prefecture+' '+(venue.address==='未確認'?'':venue.address))}`;
 return <AppShell><main id="main" className="pageMain"><nav className="breadcrumbs" aria-label="パンくずリスト"><SearchBackLink/><span>/</span><Link href={`/?prefecture=${encodeURIComponent(venue.prefecture)}`}>{venue.prefecture}</Link><span>/</span><span>{venue.name}</span></nav><section className="pageHero"><p className="eyebrow">{REGION_LABELS[venue.region]} / VENUE GUIDE</p><h1>{venue.name}</h1><p>{venue.prefecture} {venue.city}</p><div className="detailActions">{venue.officialWebsiteUrl && <a className="primaryAction" href={venue.officialWebsiteUrl} target="_blank" rel="noreferrer">公式会場情報 ↗</a>}<a className="secondaryAction" href={map} target="_blank" rel="noreferrer">地図で探す ↗</a><VenueFavorite id={venue.id} name={venue.name}/></div></section><section className="detailGrid"><article className="contentPanel"><h2>会場・アクセス</h2><dl className="detailList"><div><dt>住所</dt><dd>{venue.address}</dd></div><div><dt>アクセス</dt><dd>{venue.accessInformation ?? "未確認"}</dd></div><div><dt>キャパシティ</dt><dd>{formatNumber(venue.capacity,"人")}{venue.capacityNote && <p className="sourceDate">{venue.capacityNote}</p>}</dd></div><div><dt>ドリンク代</dt><dd>{formatNumber(venue.drinkFee,"円")}{venue.drinkFee !== null && <p className="sourceDate">ドリンク代別途の公演の場合。公演ごとの案内を優先してください。</p>}</dd></div></dl></article><article className="contentPanel"><h2>フロア・見え方</h2><p>{venue.floorDescription || "フロア構成の詳しい情報は未確認です。"}</p><dl className="detailList"><div><dt>最前列人数</dt><dd>{venue.frontRowEstimate === null ? "未確認" : `約${venue.frontRowEstimate}人`}</dd></div><div><dt>柱・視界</dt><dd>{venue.pillarInformation ?? "未確認"}</dd></div></dl><p className="detailNote">ステージの配置や見え方は公演ごとに異なります。最前列人数・柱の有無は、確認できた情報のみ掲載します。</p>{venue.officialWebsiteUrl && <a className="cardLink" href={venue.officialWebsiteUrl} target="_blank" rel="noreferrer">公式サイトでフロア情報を確認 ↗</a>}</article></section><section className="contentPanel"><div className="resultSummary"><h2>開催予定のライブ <span>{upcoming.length}件</span></h2></div>{upcoming.length ? <div className="eventList">{upcoming.map(e=><LiveEventCard key={e.id} event={e}/>)}</div> : <div className="emptyState"><p>掲載中の開催予定公演はありません。</p><p>ライブがないことを意味するものではありません。最新の予定は公式サイトでご確認ください。</p>{venue.officialWebsiteUrl && <a className="primaryAction" href={venue.officialWebsiteUrl} target="_blank" rel="noreferrer">会場公式サイトへ ↗</a>}</div>}{past.length>0 && <details style={{marginTop:24}}><summary>過去の掲載公演（{past.length}件）</summary><div className="eventList" style={{marginTop:16}}>{past.map(e=><LiveEventCard key={e.id} event={e}/>)}</div></details>}</section><section className="contentPanel"><h2>情報の出典</h2><p className="sourceDate">確認日：{venue.checkedAt} · 自動更新ではありません</p><ul className="sourceLinks">{venue.sources.map((s,i)=><li key={i}><a href={s.url} target="_blank" rel="noreferrer">{s.label} ↗</a><div className="sourceDate">{s.fields}</div></li>)}</ul></section><SearchBackLink/></main></AppShell>;
}
